environment:
  SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/tool_db
  SPRING_DATASOURCE_USERNAME: root
  SPRING_DATASOURCE_PASSWORD: root
  SERVER_PORT: 8080
  MAIL_USERNAME: ${MAIL_USERNAME}
  MAIL_PASSWORD: ${MAIL_PASSWORD}